
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LITERAL_ENTERO = 41;
  public static final int LITERAL_FLOTANTE = 42;
  public static final int FIN_EXPRESION = 50;
  public static final int PARENTESIS_CIERRA = 36;
  public static final int CASE = 12;
  public static final int DIFERENTE = 31;
  public static final int RESTA = 17;
  public static final int DOS_PUNTOS = 52;
  public static final int CONTINUE = 25;
  public static final int TIPO_STRING = 6;
  public static final int FOR = 10;
  public static final int IDENTIFICADOR = 44;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int IGUAL = 30;
  public static final int OR = 33;
  public static final int CORCHETE_CIERRA = 39;
  public static final int INCREMENTO = 23;
  public static final int SUMA = 16;
  public static final int MAIN = 40;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int TIPO_ENTERO = 2;
  public static final int DECREMENTO = 24;
  public static final int error = 1;
  public static final int COMA = 46;
  public static final int TIPO_CHAR = 5;
  public static final int MODULO = 20;
  public static final int MENOR = 26;
  public static final int BREAK = 14;
  public static final int LLAVE_ABRE = 47;
  public static final int ERROR = 49;
  public static final int ASIGNACION = 22;
  public static final int SWITCH = 11;
  public static final int MAYOR = 28;
  public static final int POTENCIA = 21;
  public static final int CORCHETE_ABRE = 38;
  public static final int ELSE = 8;
  public static final int READ = 51;
  public static final int LITERAL_STRING = 43;
  public static final int WHILE = 9;
  public static final int DEFAULT = 13;
  public static final int MAYOR_IGUAL = 29;
  public static final int LLAVE_CIERRA = 48;
  public static final int TIPO_BOOLEANO = 4;
  public static final int MENOR_IGUAL = 27;
  public static final int DIVISION = 19;
  public static final int LITERAL_BOOLEANO = 45;
  public static final int PARENTESIS_ABRE = 35;
  public static final int PRINT = 37;
  public static final int MULTIPLICACION = 18;
  public static final int TIPO_FLOTANTE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TIPO_ENTERO",
  "TIPO_FLOTANTE",
  "TIPO_BOOLEANO",
  "TIPO_CHAR",
  "TIPO_STRING",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "POTENCIA",
  "ASIGNACION",
  "INCREMENTO",
  "DECREMENTO",
  "CONTINUE",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "IGUAL",
  "DIFERENTE",
  "AND",
  "OR",
  "NOT",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "PRINT",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "MAIN",
  "LITERAL_ENTERO",
  "LITERAL_FLOTANTE",
  "LITERAL_STRING",
  "IDENTIFICADOR",
  "LITERAL_BOOLEANO",
  "COMA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "ERROR",
  "FIN_EXPRESION",
  "READ",
  "DOS_PUNTOS"
  };
}

