
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FIN_EXPRESION = 50;
  public static final int PARENTESIS_CIERRA = 49;
  public static final int ENTERO = 2;
  public static final int CASE = 13;
  public static final int DIFERENTE = 32;
  public static final int RESTA = 19;
  public static final int DOS_PUNTOS = 17;
  public static final int LIT_CADENA = 43;
  public static final int FOR = 11;
  public static final int IDENTIFICADOR = 51;
  public static final int NOT = 35;
  public static final int AND = 33;
  public static final int IGUAL = 31;
  public static final int CARACTER = 4;
  public static final int OR = 34;
  public static final int CORCHETE_CIERRA = 38;
  public static final int INCREMENTO = 25;
  public static final int SUMA = 18;
  public static final int MAIN = 39;
  public static final int IF = 8;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int DECREMENTO = 26;
  public static final int error = 1;
  public static final int COMA = 7;
  public static final int CADENA = 5;
  public static final int MODULO = 22;
  public static final int MENOR = 27;
  public static final int LIT_CHAR = 44;
  public static final int BREAK = 15;
  public static final int LLAVE_ABRE = 46;
  public static final int ERROR = 52;
  public static final int ASIGNACION = 24;
  public static final int SWITCH = 12;
  public static final int MAYOR = 29;
  public static final int POTENCIA = 23;
  public static final int CORCHETE_ABRE = 37;
  public static final int LIT_FLOTANTE = 42;
  public static final int ELSE = 9;
  public static final int READ = 40;
  public static final int WHILE = 10;
  public static final int DEFAULT = 14;
  public static final int MAYOR_IGUAL = 30;
  public static final int LIT_ENTERO = 41;
  public static final int BOOLEANO = 6;
  public static final int LIT_BOOL = 45;
  public static final int LLAVE_CIERRA = 47;
  public static final int MENOR_IGUAL = 28;
  public static final int DIVISION = 20;
  public static final int PARENTESIS_ABRE = 48;
  public static final int FLOTANTE = 3;
  public static final int PRINT = 36;
  public static final int MULTIPLICACION = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "FLOTANTE",
  "CARACTER",
  "CADENA",
  "BOOLEANO",
  "COMA",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "DOS_PUNTOS",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "MODULO",
  "POTENCIA",
  "ASIGNACION",
  "INCREMENTO",
  "DECREMENTO",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "IGUAL",
  "DIFERENTE",
  "AND",
  "OR",
  "NOT",
  "PRINT",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "MAIN",
  "READ",
  "LIT_ENTERO",
  "LIT_FLOTANTE",
  "LIT_CADENA",
  "LIT_CHAR",
  "LIT_BOOL",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "FIN_EXPRESION",
  "IDENTIFICADOR",
  "ERROR"
  };
}

